//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  F:\410NEW\application\AddTolerance.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: ZWL
//              Version: NX 7.5
//              Date: 08-24-2010  (Format: mm-dd-yyyy)
//              Time: 10:28 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using NXOpen;
using NXOpen.BlockStyler;
using TDPPM;

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
namespace TDPPM
{
    public class AddTolerance
    {
        //class members
        private static Session theSession = null;
        private static UI theUI = null;
        public static AddTolerance theAddTolerance;
        private string theDialogName;
        private NXOpen.BlockStyler.BlockDialog theDialog;
        private NXOpen.BlockStyler.UIBlock group0;// Block type: Group
        private NXOpen.BlockStyler.UIBlock selection0;// Block type: Selection
        private NXOpen.BlockStyler.UIBlock group;// Block type: Group
        private NXOpen.BlockStyler.UIBlock enum0;// Block type: Enumeration
        private NXOpen.BlockStyler.UIBlock doubleup;// Block type: Double
        private NXOpen.BlockStyler.UIBlock doubledown;// Block type: Double
        private NXOpen.BlockStyler.UIBlock double0;// Block type: Double
        private NXOpen.BlockStyler.UIBlock group01;// Block type: Group
        private NXOpen.BlockStyler.UIBlock enum01;// Block type: Enumeration
        private NXOpen.BlockStyler.UIBlock label0;// Block type: Label
        private NXOpen.BlockStyler.UIBlock label01;// Block type: Label
        private NXOpen.BlockStyler.UIBlock group1;// Block type: Group
        private NXOpen.BlockStyler.ListBox list_box0;// Block type: List Box
        public static readonly int SnapPointTypesEnabled_UserDefined = (1 << 0);
        public static readonly int SnapPointTypesEnabled_Inferred = (1 << 1);
        public static readonly int SnapPointTypesEnabled_ScreenPosition = (1 << 2);
        public static readonly int SnapPointTypesEnabled_EndPoint = (1 << 3);
        public static readonly int SnapPointTypesEnabled_MidPoint = (1 << 4);
        public static readonly int SnapPointTypesEnabled_ControlPoint = (1 << 5);
        public static readonly int SnapPointTypesEnabled_Intersection = (1 << 6);
        public static readonly int SnapPointTypesEnabled_ArcCenter = (1 << 7);
        public static readonly int SnapPointTypesEnabled_QuadrantPoint = (1 << 8);
        public static readonly int SnapPointTypesEnabled_ExistingPoint = (1 << 9);
        public static readonly int SnapPointTypesEnabled_PointonCurve = (1 << 10);
        public static readonly int SnapPointTypesEnabled_PointonSurface = (1 << 11);
        public static readonly int SnapPointTypesEnabled_PointConstructor = (1 << 12);
        public static readonly int SnapPointTypesEnabled_TwocurveIntersection = (1 << 13);
        public static readonly int SnapPointTypesEnabled_TangentPoint = (1 << 14);
        public static readonly int SnapPointTypesEnabled_Poles = (1 << 15);
        public static readonly int SnapPointTypesEnabled_BoundedGridPoint = (1 << 16);
        public static readonly int SnapPointTypesOnByDefault_EndPoint = (1 << 3);
        public static readonly int SnapPointTypesOnByDefault_MidPoint = (1 << 4);
        public static readonly int SnapPointTypesOnByDefault_ControlPoint = (1 << 5);
        public static readonly int SnapPointTypesOnByDefault_Intersection = (1 << 6);
        public static readonly int SnapPointTypesOnByDefault_ArcCenter = (1 << 7);
        public static readonly int SnapPointTypesOnByDefault_QuadrantPoint = (1 << 8);
        public static readonly int SnapPointTypesOnByDefault_ExistingPoint = (1 << 9);
        public static readonly int SnapPointTypesOnByDefault_PointonCurve = (1 << 10);
        public static readonly int SnapPointTypesOnByDefault_PointonSurface = (1 << 11);
        public static readonly int SnapPointTypesOnByDefault_PointConstructor = (1 << 12);

        //------------------------------------------------------------------------------
        //Constructor for NX Styler class
        //------------------------------------------------------------------------------
        public AddTolerance()
        {
            try
            {
                theSession = Session.GetSession();
                theUI = UI.GetUI();
                theDialogName = "AddTolerance.dlx";
                theDialog = theUI.CreateDialog(theDialogName);
                theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(ApplyCB));
                theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
                theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
                theDialog.AddCancelHandler(new NXOpen.BlockStyler.BlockDialog.Cancel(cancel_cb));
                theDialog.AddFilterHandler(new NXOpen.BlockStyler.BlockDialog.Filter(filter_cb));
                theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(InitializeCB));
                theDialog.AddFocusNotifyHandler(new NXOpen.BlockStyler.BlockDialog.FocusNotify(focusNotify_cb));
                theDialog.AddKeyboardFocusNotifyHandler(new NXOpen.BlockStyler.BlockDialog.KeyboardFocusNotify(keyboardFocusNotify_cb));
                theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
            }
            catch (Exception ex)
            {
                NXFun.MessageBox(ex.Message);
            }
        }
        public static void MainFun()
        {
            try
            {
                theAddTolerance = new AddTolerance();
                theAddTolerance.Show();
            }
            catch (Exception ex)
            {
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            finally
            {
                theAddTolerance.Dispose();
            }
        }

        //------------------------------------------------------------------------------
        //This method shows the dialog on the screen
        //------------------------------------------------------------------------------
        public NXOpen.UIStyler.DialogResponse Show()
        {
            try
            {
                theDialog.Show();
            }
            catch (Exception ex)
            {
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return 0;
        }

        //------------------------------------------------------------------------------
        //Method Name: Dispose
        //------------------------------------------------------------------------------
        public void Dispose()
        {
            if (theDialog != null)
            {
                theDialog.Dispose();
                theDialog = null;
            }
        }


        //------------------------------------------------------------------------------
        //Callback Name: InitializeCB
        //------------------------------------------------------------------------------
        public void InitializeCB()
        {
            try
            {
                group0 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("group0");
                selection0 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("selection0");
                group = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("group");
                enum0 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("enum0");
                doubleup = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("doubleup");
                doubledown = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("doubledown");
                double0 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("double0");
                group01 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("group01");
                enum01 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("enum01");
                label0 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("label0");
                label01 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("label01");
                group1 = (NXOpen.BlockStyler.UIBlock)theDialog.TopBlock.FindBlock("group1");
                list_box0 = (NXOpen.BlockStyler.ListBox)theDialog.TopBlock.FindBlock("list_box0");
            }
            catch (Exception ex)
            {
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

        //------------------------------------------------------------------------------
        //Callback Name: dialogShown_cb
        //------------------------------------------------------------------------------
        public void dialogShown_cb()
        {
            try
            {
            }
            catch (Exception ex)
            {
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

        //------------------------------------------------------------------------------
        //Callback Name: ApplyCB
        //------------------------------------------------------------------------------
        public int ApplyCB()
        {
            int errorCode = 0;
            try
            {
                TaggedObject[] obs = selection0.GetProperties().GetTaggedObjectVector("SelectedObjects");
                if (obs.Length == 0)
                {
                    theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Warning, "请选择尺寸");
                    return 1;
                }
                double upper = doubleup.GetProperties().GetDouble("Value");
                double lower = doubledown.GetProperties().GetDouble("Value");
                NXOpen.Annotations.Dimension d = (NXOpen.Annotations.Dimension)obs[0];
                NXFun.SetDimensionTolerance(d, upper, lower);
            }
            catch (Exception ex)
            {
                errorCode = 1;
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return errorCode;
        }

        //------------------------------------------------------------------------------
        //Callback Name: update_cb
        //------------------------------------------------------------------------------
        public int FindTol()
        {
            TaggedObject[] obs = selection0.GetProperties().GetTaggedObjectVector("SelectedObjects");
            if (obs.Length == 0)
            {
                return 0;
            }
            NXOpen.Annotations.Dimension d = (NXOpen.Annotations.Dimension)obs[0];
            double dim = NXFun.GetDimensionValue(d);
            double0.GetProperties().SetDouble("Value", dim);
            string type = enum0.GetProperties().GetEnumAsString("Value");
            double upper, lower;
            if (!XML3DPPM.GetTolerance(dim, type, out upper, out lower, NXFun.TDPPMPath + "HB5800.xml"))
            {
                theUI.NXMessageBox.Show("提示", NXMessageBox.DialogType.Error, "没有查询到该尺寸的相关公差，请手动填写！");
            }
            doubleup.GetProperties().SetDouble("Value", upper);
            doubledown.GetProperties().SetDouble("Value", lower);
            return 1;
        }
        public int FindTol(double dim)
        {
            double0.GetProperties().SetDouble("Value", dim);
            string type = enum0.GetProperties().GetEnumAsString("Value");
            double upper, lower;
            if (!XML3DPPM.GetTolerance(dim, type, out upper, out lower, NXFun.TDPPMPath + "HB5800.xml"))
            {
                theUI.NXMessageBox.Show("提示", NXMessageBox.DialogType.Error, "没有查询到该尺寸的相关公差，请手动填写！");
            }
            doubleup.GetProperties().SetDouble("Value", upper);
            doubledown.GetProperties().SetDouble("Value", lower);
            return 1;
        }
        public int update_cb(NXOpen.BlockStyler.UIBlock block)
        {
            try
            {
                if (block == selection0)
                {
                    //查询公差
                    FindTol();
                }
                else if (block == enum0)
                {
                    FindTol();
                }
                else if (block == doubleup)
                {
                }
                else if (block == doubledown)
                {
                }
                else if (block == double0)
                {
                    //手动输入时，自动查询公差
                    double dim = double0.GetProperties().GetDouble("Value");
                    FindTol(dim);
                }
                else if (block == enum01)
                {
                    string table = enum01.GetProperties().GetEnumAsString("Value");
                    if (table == "表1")
                    {
                        label0.GetProperties().SetLogical("Show", true);
                        label01.GetProperties().SetLogical("Show", false);
                    }
                    else if (table == "表4")
                    {
                        label0.GetProperties().SetLogical("Show", false);
                        label01.GetProperties().SetLogical("Show", true);
                    }
                }
                else if (block == label0)
                {
                }
                else if (block == label01)
                {
                }
                else if (block == list_box0)
                {
                }
            }
            catch (Exception ex)
            {
                theUI.NXMessageBox.Show("提示", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return 0;
        }

        //------------------------------------------------------------------------------
        //Callback Name: ok_cb
        //------------------------------------------------------------------------------
        public int ok_cb()
        {
            int errorCode = 0;
            try
            {
                errorCode = ApplyCB();
            }
            catch (Exception ex)
            {
                errorCode = 1;
                theUI.NXMessageBox.Show("提示", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return errorCode;
        }

        //------------------------------------------------------------------------------
        //Callback Name: cancel_cb
        //------------------------------------------------------------------------------
        public int cancel_cb()
        {
            try
            {

            }
            catch (Exception ex)
            {
                theUI.NXMessageBox.Show("提示", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return 0;
        }

        //------------------------------------------------------------------------------
        //Callback Name: filter_cb
        //------------------------------------------------------------------------------
        public int filter_cb(NXOpen.BlockStyler.UIBlock block, NXOpen.TaggedObject selectedObject)
        {
            if (block == selection0)
            {
                try
                {
                    NXOpen.Annotations.Dimension d = (NXOpen.Annotations.Dimension)selectedObject;
                }
                catch
                {
                    return (NXOpen.UF.UFConstants.UF_UI_SEL_REJECT);
                }
            }

            return (NXOpen.UF.UFConstants.UF_UI_SEL_ACCEPT);
        }

        //------------------------------------------------------------------------------
        //Callback Name: focusNotify_cb
        //------------------------------------------------------------------------------
        public void focusNotify_cb(NXOpen.BlockStyler.UIBlock block, bool focus)
        {
            try
            {
            }
            catch (Exception ex)
            {
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

        //------------------------------------------------------------------------------
        //Callback Name: keyboardFocusNotify_cb
        //------------------------------------------------------------------------------
        public void keyboardFocusNotify_cb(NXOpen.BlockStyler.UIBlock block, bool focus)
        {
            try
            {
            }
            catch (Exception ex)
            {
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

    }
}